# Generated by Django 5.1.1 on 2024-11-24 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_hobbies_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(
                blank=True, default=None, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="hobbies",
            field=models.ManyToManyField(blank=True, default=None, to="api.hobbies"),
        ),
        migrations.AlterField(
            model_name="user",
            name="pending_requests",
            field=models.ManyToManyField(
                blank=True, default=None, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default.jpg",
                upload_to="profile_images/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sent_requests",
            field=models.ManyToManyField(
                blank=True, default=None, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
