# Generated by Django 5.1.4 on 2025-01-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/api/spa/assets/default.jpg', upload_to='static/api/spa/assets/'),
        ),
    ]
