# Generated by Django 5.1.1 on 2024-12-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hobbies",
            name="description",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="hobbies",
            name="name",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=254),
        ),
    ]
