# Generated by Django 5.1.1 on 2024-12-10 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_hobbies_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=254,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
